// User Action Types
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// Profile Action Types
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL';

// User Requests Action Types
export const USER_REQUESTS_REQUEST = 'USER_REQUESTS_REQUEST';
export const USER_REQUESTS_SUCCESS = 'USER_REQUESTS_SUCCESS';
export const USER_REQUESTS_FAIL = 'USER_REQUESTS_FAIL';
export const USER_REQUEST_CREATE_REQUEST = 'USER_REQUEST_CREATE_REQUEST';
export const USER_REQUEST_CREATE_SUCCESS = 'USER_REQUEST_CREATE_SUCCESS';
export const USER_REQUEST_CREATE_FAIL = 'USER_REQUEST_CREATE_FAIL';
export const USER_REQUEST_UPDATE_REQUEST = 'USER_REQUEST_UPDATE_REQUEST';
export const USER_REQUEST_UPDATE_SUCCESS = 'USER_REQUEST_UPDATE_SUCCESS';
export const USER_REQUEST_UPDATE_FAIL = 'USER_REQUEST_UPDATE_FAIL';

 